#pragma once
#include "Skill_LeafShot.h"
#include "Skill_FireBall.h"
#include "Skill_WaterCannon.h"
#include "Skill_Blaze.h"


#include "Skill_Tornado.h"
#include "Skill_Rush.h"
#include "Skill_TearsShot.h"
//#include "Skill_TearsShot.h"
#include "Skill_CrossShot.h"
#include "Skill_XShot.h"
#include "Skill_WebShot.h"
#include "Skill_SnowRain.h"
#include "Skill_SnowVulcan.h"
#include "Skill_SnowFall.h"
#include "Skill_SnowCrystal.h"
#include "Skill_BubbleShot.h"
#include "Skill_AccelWater.h"
#include "Skill_XClaw.h"
#include "Skill_HealBubble.h"