#pragma once

namespace PKH
{
	enum class TextureKey
	{
		NONE,
		SKY_U,
		SKY_D,
		SKY_L,
		SKY_R,
		SKY_F,
		SKY_B,
		CURSOR_TARGET,
		LOCK_ON,

		BUTTER_WALK_D_01,
		BUTTER_WALK_D_02,
		BUTTER_WALK_D_03,
		BUTTER_WALK_LD_01,
		BUTTER_WALK_LD_02,
		BUTTER_WALK_LD_03,
		BUTTER_WALK_L_01,
		BUTTER_WALK_L_02,
		BUTTER_WALK_L_03,
		BUTTER_WALK_LU_01,
		BUTTER_WALK_LU_02,
		BUTTER_WALK_LU_03,
		BUTTER_WALK_U_01,
		BUTTER_WALK_U_02,
		BUTTER_WALK_U_03,

		BUTTER_ATTACK_D_01,
		BUTTER_ATTACK_D_02,
		BUTTER_ATTACK_LD_01,
		BUTTER_ATTACK_LD_02,
		BUTTER_ATTACK_L_01,
		BUTTER_ATTACK_L_02,
		BUTTER_ATTACK_LU_01,
		BUTTER_ATTACK_LU_02,
		BUTTER_ATTACK_U_01,
		BUTTER_ATTACK_U_02,

		CATER_WALK_D_01,
		CATER_WALK_D_02,
		CATER_WALK_D_03,
		CATER_WALK_LD_01,
		CATER_WALK_LD_02,
		CATER_WALK_LD_03,
		CATER_WALK_L_01,
		CATER_WALK_L_02,
		CATER_WALK_L_03,
		CATER_WALK_LU_01,
		CATER_WALK_LU_02,
		CATER_WALK_LU_03,
		CATER_WALK_U_01,
		CATER_WALK_U_02,
		CATER_WALK_U_03,
		
		CATER_ATTACK_D_01,
		CATER_ATTACK_D_02,
		CATER_ATTACK_LD_01,
		CATER_ATTACK_LD_02,
		CATER_ATTACK_L_01,
		CATER_ATTACK_L_02,
		CATER_ATTACK_LU_01,
		CATER_ATTACK_LU_02,
		CATER_ATTACK_U_01,
		CATER_ATTACK_U_02,

		//CATER_WALK_D_01,
		//CATER_WALK_D_02,
		//CATER_WALK_D_03,
		//CATER_WALK_LD_01,
		//CATER_WALK_LD_02,
		//CATER_WALK_LD_03,
		//CATER_WALK_L_01,
		//CATER_WALK_L_02,
		//CATER_WALK_L_03,
		//CATER_WALK_LU_01,
		//CATER_WALK_LU_02,
		//CATER_WALK_LU_03,
		//CATER_WALK_U_01,
		//CATER_WALK_U_02,
		//CATER_WALK_U_03,

		//CATER_ATTACK_D_01,
		//CATER_ATTACK_D_02,
		//CATER_ATTACK_LD_01,
		//CATER_ATTACK_LD_02,
		//CATER_ATTACK_L_01,
		//CATER_ATTACK_L_02,
		//CATER_ATTACK_LU_01,
		//CATER_ATTACK_LU_02,
		//CATER_ATTACK_U_01,
		//CATER_ATTACK_U_02,
	};

	enum class TextureType
	{
		DEFAULT,
		CUBE,
	};
	
	class Texture
	{
	public:
		Texture();
		~Texture();

		int GetSpriteWidth()const;
		int GetSpriteHeight()const;

		LPDIRECT3DTEXTURE9 pTexture = nullptr;
		D3DXIMAGE_INFO imageInfo;
		DWORD rowCount = 1;
		DWORD colCount = 1;
	};


}
